### ISSUE TITLE
swapgs mitigations: how to patch entry_64.S using livepatch

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#1015]
KernelCare (www.kernelcare.com) has announced live patches for swapgs - i expect they use the normal / default kernel livepatching interface.

How is it possible to build a livepatch containing section changes like here:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.19.65&id=befb822c062b4c3d93380a58d5fd479395e8b267

**Comment by jpoimboe** [comment]
I have an idea for how to do it, but I don't necessarily have the time to test it out.  I'll share the idea here if you promise to try it out and post the results :-)

**Comment by disaster123** [comment]
Yes I will.

**Comment by disaster123** [comment]
Oh i forgot I promise ;-)

**Comment by jpoimboe** [comment]
It's going to be tricky, but I don't know of any technical blockers.

I haven't tried it, but the idea I had was to manually patch the asm entry code, using text_poke_bp() from a pre-patch callback to replace an instruction with a jmp to the new code.  The text_poke_bp() handler and the new code could both be the same -- something like the following "trampoline":
```
<original replaced insn>
lfence
jmp <back to entry code right after original replaced insn>
```
You would need one of those trampolines for each of the patch sites, since the jmp address would be different for each one.  A trampoline can be created by either

- a) using inline asm (and manually text_poke() the jump destination at runtime); or
- b) generating the trampoline on the fly (but this requires allocating executable memory).

I think a) may be easier.

Note that text_poke_bp() requires that the original replaced instruction *must* be a single instruction, so it needs to be at least 5 bytes (length of a jmp instruction).

Beforehand, in the pre-patch callback, you could find the code locations of the patch sites using kallsyms, and then read the to-be-patched instruction to verify it's what you expect.  Some math would be needed to calculate the jump offsets.

A similar idea would be to use stop_machine() instead of text_poke_bp(), and patch the instruction directly, but that introduces a lot more latency and you'd have to be careful about NMIs.

Let me know if you have any questions.  I'd be glad to help review it.  AFAIK, RH has no current plans to livepatch this issue, but at the very least it would be a great example for the patch author guide.

**Comment by jpoimboe** [comment]
On second thought, I don't think text_poke_bp() is safe for this particular patch because it affects the exception entry path.  So in the very very rare case where an application triggers a debugging int3 breakpoint right when the patch is being applied, it could double fault.  So stop_machine() may be the only way to go.

**Comment by disaster123** [comment]
ouch - ok this sounds interesting but is beyond my skills. I can adapt / backport patches and even implement the shadow stuff but i have no idea how to use stop_machine and patch instructions directly means.

**Comment by disaster123** [comment]
KernelCare told me that they can do it as they use their own kernel module.

Code is here: http://patches.kernelcare.com/kmod_kcare.tar.gz

**Comment by jpoimboe** [comment]
If you tried, it'd be a great learning experience.  I want to do it, but don't currently have the time.  Maybe somebody else will give it a shot.  That kernelcare code looks like it's just part of the patching infrastructure, not anything swapgs related.
