### ISSUE TITLE
kmod/relocations: Missing + r_addend

### ISSUE THREAD

**Issue by stettberger** [dynup/kpatch#1093]
I think in the calculation of the relocation, a + addend is missing to implement R_X86_64_64 correctly.

https://github.com/dynup/kpatch/blob/8e8707ed723adf8226e99563b88c5490ca51a7e0/kmod/core/core.c#L745

**Comment by joe-lawrence** [comment]
Yeah, the [AMD64 ABI draft doc]( http://refspecs.linuxfoundation.org/elf/x86_64-abi-0.99.pdf ), Table 4.10: Relocation Types table lists that relocation type as: `R_X86_64_64 ... S + A`, so it looks like we're missing the addend for this type.  Do you happen to have an input kpatch that generates one of these relocations?

**Comment by stettberger** [comment]
Unfortunately not. I just read the source code and stumpled upon this issue.

**Comment by jpoimboe** [comment]
Nicely spotted 6-year-old bug :-)  This code is deprecated but it wouldn't hurt to fix it (just a one-line change).

**Comment by euspectre** [comment]
Thanks for the fix!

Looks like such dynrelas are extremely rare but, in theory, are possible. I haven't seen these in the wild yet but they can appear if the patch module uses, say, a non-exported global variable from vmlinux with an appropriate addend.

I came up with the following (quite contrived) source patch to reproduce the issue:

```
diff --git a/fs/proc/meminfo.c b/fs/proc/meminfo.c
index 32512c4fa9c0..2f2f320950fe 100644
--- a/fs/proc/meminfo.c
+++ b/fs/proc/meminfo.c
@@ -17,6 +17,7 @@
 #include <asm/page.h>
 #include <asm/pgtable.h>
 #include <bc/beancounter.h>
+#include <asm/desc.h>
 #include "internal.h"
 
 void __attribute__((weak)) arch_report_meminfo(struct seq_file *m)
@@ -283,6 +284,7 @@ static int meminfo_proc_show(struct seq_file *m, void *v)
 
 static int meminfo_proc_open(struct inode *inode, struct file *file)
 {
+	pr_info("[DBG] idt_table+offset=%lu\n", (unsigned long)&idt_table+0x80000000);
 	return single_open(file, meminfo_proc_show, NULL);
 }
 
```
Checked the patch with a VZ kernel, which is based on 3.10.0-1062.12.1.el7 from RHEL.

`(unsigned long)&idt_table+0x80000000` is calculated using R_X86_64_64 dynrela with addend 0x80000000.

Without the fix, `&idt_table` is printed, which is wrong. With the fix, `&idt_table+0xffffffff80000000` is printed, which is also wrong but due to a separate issue, similar to https://github.com/dynup/kpatch/issues/1064 (addend should be long rather than int). I'll prepare a patch for it.

Anyway, the fix works, which is good.
