### ISSUE TITLE
Do I need to unload all patching module when system reboot?

### ISSUE THREAD

**Issue by longyuwlz** [dynup/kpatch#1103]
When I used kpatch，I just built a kernel patching module about /proc/meminfo. When I loaded the patching module then reboot the system. After system started, I found some process couldn't work nomally.

Do I need to unload all patcing module when system reboot?

**Comment by yhcote** [comment]
You can "uninstall" the livepatch module and load it on demand instead of it being done automatically at boot time, but with the information I have from your query, it seems like your kpatch-patch has some issues. It usually should work when loading at boot time. Maybe there's a sequence / timing issue you need to look into?

**Comment by longyuwlz** [comment]
In my situation after reboot, the system will not load livepatch automatically. I haven't installed livepatch yet, but just used it for testing.

In my testing, I replaced new kernel bzImage at the same time, it would take effect when system rebooted.

I want to known should I unload all patching modules when system reboot?

**Comment by jpoimboe** [comment]
Do you mean unload before rebooting?  It shouldn't be necessary.  In general unloading should be avoided because it adds more risk.

**Comment by longyuwlz** [comment]
I got it. Thanks!
