### ISSUE TITLE
kpatch-test should ignore older kernel log messages

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1133]
The kpatch-test script looks at the entire dmesg log on completion and will report failure if there are any "Call Trace" entries.

We should adopt a partial log scraping technique like [[PATCH] selftests/livepatch: Use "comm" instead of "diff" for dmesg](https://lore.kernel.org/live-patching/20200714075307.GF20226@alley/T/#md82c3fd884d176654f5f9874843866f09ce15dbd) so that the tests ignores unrelated error messages.

**Comment by sm00th** [comment]
We actually already cleanup dmesg before testing which achieves the same result. The problem is we do this before building the modules which can take a lot of time and give a lot of opportunities for other problems to sneak in. I don't think we expect to trigger any call traces during build so maybe just move that dmesg buffer clear right before load/unload part of the test?
