### ISSUE TITLE
can kpatch support  static key while kernel live patch can't ?

### ISSUE THREAD

**Issue by xiejingf** [dynup/kpatch#1150]
As mentioned in #940 , jump label support still can not work for kernel live patch because it might require upstream kernel changes,   the create-diff-object tools handle both klp and  kpatch, so it is best for it to warn static key usage.

If my use case is all kpatch-based (kpatch.ko),  no kernel live patch is involved,   can I confirm that it is OK to include jump label as did in [d8f359a38c96]( https://github.com/jpoimboe/kpatch/commit/d8f359a38c96ef4eec2c83f5755bbeb5597d60fa )  (create-diff-object: add jump label support).

Please help clarify,   thanks in advance~~

**Comment by euspectre** [comment]
I think, there is little interest in implementing support for static keys / jump labels / whatever in kpatch.ko-based patches. It is easier to maintain the same code for kpatch.ko and livepatch.

kpatch.ko is deprecated anyway.

We still use it though, but I would not guarantee that support for static keys (as of "create-diff-object: add jump label support") always works correctly there. It did work in my particular case (https://github.com/dynup/kpatch/issues/931), but still.

Strange enough, I eventually found it easier to maintain if I rewrite static branches in the patched code to check the values explicitly (static_key_enabled(), etc.) This can require touching more code though.

**Comment by xiejingf** [comment]
> I think, there is little interest in implementing support for static keys / jump labels / whatever in kpatch.ko-based patches. It is easier to maintain the same code for kpatch.ko and livepatch.
> 
> kpatch.ko is deprecated anyway.
> 
> We still use it though, but I would not guarantee that support for static keys (as of "create-diff-object: add jump label support") always works correctly there. It did work in my particular case (#931), but still.
> 
> Strange enough, I eventually found it easier to maintain if I rewrite static branches in the patched code to check the values explicitly (static_key_enabled(), etc.) This can require touching more code though.

1. quick read the case #931 , it seems the patch ( as of "create-diff-object: add jump label support") works, I can see from the comment by you  that `'no crashes seen so far, and the jump label state gets switched in the patched function'`  :)
2. Yes, it is sure that more code should be rewrite in the patch in order to get the correct value of static key, and that is **quite annoying, sometimes error-prone,  even cause a lot of changed functions..**

**Comment by euspectre** [comment]
> quick read the case #931 , it seems the patch ( as of "create-diff-object: add jump label support") works

Exactly. In worked OK in that particular case but I cannot guarantee it will work in any other case where static keys or other jump labels are used.

**Comment by xiejingf** [comment]
> > quick read the case #931 , it seems the patch ( as of "create-diff-object: add jump label support") works
> 
> Exactly. In worked OK in that particular case but I cannot guarantee it will work in any other case where static keys or other jump labels are used.

Thanks !
As far as I know, for the kpatch.ko based patches, all the static key stuff were done by the kernel module loading codes (jump_label_module_notify), so it might be safe in include those jump table sections as a normal kernel module would do .

@jpoimboe , any advice or thoughts ?

**Comment by jpoimboe** [comment]
@xiejing, jump_label_module_notify() isn't the only static key init function.  There's also **jump_label_apply_nops()**.

I believe your approach could only work about **half** the time: only in the case where the initial static branch instruction is a **JMP** (not a **NOP**).

A NOP is supposed to get written by jump_label_apply_nops(), which needs the __jump_table to have its relocations (written by kpatch_write_relocations()) beforehand.  But kpatch_write_relocations() gets called by the module coming notifier **after** jump_label_apply_nops(), not before.  So jump_label_apply_nops() sees a corrupt table and doesn't do anything, and the NOPs remain as JMPs.

Either of the following cases should work (I think) because the initial static branch instruction is a JMP:

- DEFINE_STATIC_KEY_FALSE(key) + if static_branch_likely(&key))
- DEFINE_STATIC_KEY_TRUE(key) + if (static_branch_unlikely(&key))

If the initial static branch instruction is a NOP, it will **not** work.  That means either of the following cases should **not** work:

- DEFINE_STATIC_KEY_FALSE(key) + if static_branch_unlikely(&key))
- DEFINE_STATIC_KEY_TRUE(key) + if (static_branch_likely(&key))

I fixed this ordering problem for livepatch starting with Linux 5.8 (see #1089), but there's no way to fix it for kpatch.ko.
