### ISSUE TITLE
Exluding module build (i.e. -t vmlinux), fails.

### ISSUE THREAD

**Issue by luckycat889** [dynup/kpatch#1202]
Hello,
I notice if one wants to run '-t vmlinux' it doesn't work, since the latest kpatch-build expects the presence of Module.symvers, as per the following line:
cp -f "$SRCDIR/Module.symvers" "$TEMPDIR/Module.symvers" || die

I'd like to have the option to exclude the modules, since it takes forever to build. I'll experiment a bit

**Comment by luckycat889** [comment]
So for Ubuntu for instance, building 'vmlinux modules' takes an order of magnitude longer than only 'vmlinux'.
A simple way of circumventing an unnecessary 'modules' build (in case you are patching kernel and no drivers), is to copy the .deb provided Modules.symvers to the source location (ex for ubuntu 20.04)
$ apt-get source linux-image-unsigned-5.8.0-63-generic
$ cp /boot/config-5.8.0-63-generic linux-hwe-5.8-5.8.0/.config
$ (cd linux-hwe-5.8-5.8.0 && make olddefconfig)
$ cp /usr/src/linux-headers-5.8.0-63-generic/Module.symvers linux-hwe-5.8-5.8.0
$ time kpatch-build -t vmlinux --skip-cleanup -v /usr/lib/debug/boot/vmlinux-5.8.0-63-generic -s /home/user/dev/patch/linux-hwe-5.8-5.8.0 uptime.patch

**Comment by jpoimboe** [comment]
I suspect this problem only exists when using the --sourcedir option.  Otherwise, when patching a distro-built kernel, that file is distributed in the kernel-devel package or similar.  For relocation handling, we need to know which symbols are exported, even for vmlinux-only patches, so I'm not sure there will be any way around this limitation, other than the solution you found of manually copying Module.symvers.
