### ISSUE TITLE
support patching __init functions in kernel modules

### ISSUE THREAD

**Issue by arges** [dynup/kpatch#538]
Patching __init functions for kernel modules should work. In the case that the module is unloaded, patching __init should work since the klp MODULE_COMING notifier triggers before __init gets executed in that module.

Another approach would be to just build the fixed module and spit it out somewhere. Then it could be left as an exercise to the reader to overwrite the faulty module on disk.

**Comment by jpoimboe** [comment]
> Patching __init functions for kernel modules should work. In the case that the module is unloaded, patching __init should work since the klp MODULE_COMING notifier triggers before __init gets executed in that module.

I just responded to Jiri's suggestion about this on the live patching list.  It actually isn't possible because __init functions don't have the __fentry call which ftrace needs to hook into to patch a function.

> Another approach would be to just build the fixed module and spit it out somewhere. Then it could be left as an exercise to the reader to overwrite the faulty module on disk.

This is definitely possible, but IMO, it's outside the scope of what kpatch-build should do.  In this case the module can just be rebuilt normally in the kernel tree.

**Comment by arges** [comment]
Ok seems reasonable to close this issue then. Thanks
