### ISSUE TITLE
Error: data section .data..read_mostly selected for inclusion

### ISSUE THREAD

**Issue by rosslagerwall** [dynup/kpatch#553]
The following patch fails to compile against 3.10.0-229.14.1.el7.x86_64:
```
diff --git a/arch/x86/kernel/acpi/boot.c b/arch/x86/kernel/acpi/boot.c
index 45a51de..3b6852f 100644
--- a/arch/x86/kernel/acpi/boot.c
+++ b/arch/x86/kernel/acpi/boot.c
@@ -108,9 +108,7 @@ static unsigned int gsi_to_irq(unsigned int gsi)
 	unsigned int i;
 
 	for (i = 0; i < NR_IRQS_LEGACY; i++) {
-		if (isa_irq_to_gsi[i] == gsi) {
-			return i;
-		}
+		printk("%u\n", isa_irq_to_gsi[i]);
 	}
 
 	/* Provide an identity mapping of gsi == irq
```

The issue here is that the section reference to .data..read_mostly does not get replaced with the correct symbol because of the check in https://github.com/dynup/kpatch/blob/master/kpatch-build/create-diff-object.c#L1372 and the way that GCC compares the ptr with the address at the end of the array (one past the index).

```
  [90] .data..read_mostly PROGBITS        0000000000000000 0033c0 000040 00  WA  0   0 32

Relocation section '.rela.text.gsi_to_irq' at offset 0x28738 contains 6 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000001  000000b900000000 R_X86_64_NONE          0000000000000000 __fentry__ - 4
0000000000000012  000000310000000b R_X86_64_32S           0000000000000000 .data..read_mostly + 0
0000000000000027  000000120000000b R_X86_64_32S           0000000000000000 .rodata.str1.1 + 0
0000000000000030  000000d800000002 R_X86_64_PC32          0000000000000000 printk - 4
0000000000000037  000000310000000b R_X86_64_32S           0000000000000000 .data..read_mostly + 40
000000000000003f  000000df00000002 R_X86_64_PC32          0000000000000000 gsi_top - 4
```

I'm struggling to think of a decent way of fixing this. You could "bundle" the sections manually....

#define __read_mostly(name) __attribute__((__section__(".data.read_mostly." # name))) name
static u32 __read_mostly(isa_irq_to_gsi)[NR_IRQS_LEGACY] = {

**Comment by jpoimboe** [comment]
Thanks, this is an interesting problem.

At first I thought this means that our whole approach in kpatch_replace_sections_syms() is broken.  Because how can we tell the difference between the end of one variable and the beginning of the next?

But looking more, I think this can only happen in cases where the code needs the _address_ of the variable, rather than the contents of the variable itself.  And since kpatch doesn't allow changes to data sections anyway, the start address of the following variable will always be the same as the end address of the previous variable.  Therefore it would be ok if we were to pick the wrong variable in this case, since the address would be the same.

**Comment by jpoimboe** [comment]
So I think I can hack in a fix for this in kpatch_replace_sections_syms(), to check for the case where a R_X86_64_32S rela is pointing to the end of a data section.

That's not ideal, though.  It make all this so much easier if we could get gcc to use real symbol references instead of section references whenever possible.

**Comment by rosslagerwall** [comment]
But this may not always occur at the end of a data section.

Consider:
```
static int arr1[NR] __read_mostly;
static int arr2[NR] __read_mostly;

void func(void)
{
    int i;

    for (i = 0; i < NR; i++) {
        printk("%d\n", arr2[i]);
    }
    printk("%p\n", &arr1[0]);

    for (i = 0; i < NR; i++) {
        printk("%d\n", arr1[i]);
    }
}
```

generates these relocations:
```
Relocation section '.rela.text.func' at offset 0x828 contains 11 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000002  0000000a0000000a R_X86_64_32            0000000000000000 .data..read_mostly + 0
0000000000000015  000000050000000a R_X86_64_32            0000000000000000 .rodata.str1.1 + 0
000000000000001e  0000001600000002 R_X86_64_PC32          0000000000000000 printk - 4
0000000000000025  0000000a0000000b R_X86_64_32S           0000000000000000 .data..read_mostly + 40
000000000000002c  0000000a0000000a R_X86_64_32            0000000000000000 .data..read_mostly + 40
0000000000000031  000000050000000a R_X86_64_32            0000000000000000 .rodata.str1.1 + 4
0000000000000038  0000000a0000000a R_X86_64_32            0000000000000000 .data..read_mostly + 40
000000000000003d  0000001600000002 R_X86_64_PC32          0000000000000000 printk - 4
000000000000004d  000000050000000a R_X86_64_32            0000000000000000 .rodata.str1.1 + 0
0000000000000056  0000001600000002 R_X86_64_PC32          0000000000000000 printk - 4
000000000000005d  0000000a0000000b R_X86_64_32S           0000000000000000 .data..read_mostly + 80
```

Although gcc hasn't done it, it seems possible that it could have only generated one relocation for .data..read_mostly + 40 and used it to refer to two different variables. This makes me think that somehow we shouldn't need to know exactly which symbol we're using to refer to the data.

**Comment by rosslagerwall** [comment]
Also, looking at those relocations, shouldn't kpatch_replace_sections_syms also handle R_X86_64_32?

**Comment by jpoimboe** [comment]
> But this may not always occur at the end of a data section.

Right, that's the point I was trying to make.  If it happens in the middle of a data section, then we'll just pick the wrong symbol (e.g. `arr2 + 0` instead of `arr1 + 40`) .  But that's not a problem, because:

1) I think this situation only occurs when gcc is trying to get the address of the symbol, not the contents of its data; and

2) the data section won't change because kpatch doesn't allow it.  So the address of `arr2 + 0` will always be the same as the address of `arr1 + 40`.

**Comment by jpoimboe** [comment]
> Although gcc hasn't done it, it seems possible that it could have only generated one relocation for .data..read_mostly + 40 and used it to refer to two different variables. This makes me think that somehow we shouldn't need to know exactly which symbol we're using to refer to the data.

Yeah, maybe we don't need to know exactly which symbol we're using if it's in a data section, since data sections aren't supposed to change.  But I think that approach may be harder to implement because to get a reasonable error message for data section changes, we'd have to compare data sections before comparing relocations; but there's a chicken and egg problem: you can't tell for sure if a data section changed unless you compare the relocations.  It would also mean we'd have to redo our "lookup" logic to find the location of the symbol in the running kernel.

**Comment by jpoimboe** [comment]
> Also, looking at those relocations, shouldn't kpatch_replace_sections_syms also handle R_X86_64_32?

The kernel doesn't use those (except for debuginfo sections).

**Comment by jpoimboe** [comment]
> That's not ideal, though. It would make all this so much easier if we could get gcc to use real symbol references instead of section references whenever possible.

I think this is actually an assembler issue -- maybe I'll ask about it on the binutils mailing list.

**Comment by rosslagerwall** [comment]
Awesome, thanks.
