### ISSUE TITLE
[4.5-rc2] [ubuntu 15.10] error: ‘struct module’ has no member named ‘module_core/core_size/core_ro_size’

### ISSUE THREAD

**Issue by dandart** [dynup/kpatch#576]
Compiling I get errors like:

/home/kvd/kpatch/kmod/core/core.c: In function ‘kpatch_write_relocations’:
/home/kvd/kpatch/kmod/core/core.c:586:48: error: ‘struct module’ has no member named ‘module_core’
  unsigned long core = (unsigned long)kpmod->mod->module_core;
                                                ^
/home/kvd/kpatch/kmod/core/core.c:587:38: error: ‘struct module’ has no member named ‘core_size’
  unsigned long core_size = kpmod->mod->core_size;
                                      ^
/home/kvd/kpatch/kmod/core/core.c:648:30: error: ‘struct module’ has no member named ‘core_ro_size’
   if (loc < core + kpmod->mod->core_ro_size)
                              ^
compiling for a custom kernel 4.5-rc2 on ubuntu 15.10.
Could someone help me with this please

**Comment by flaming-toast** [comment]
Unfortunately the kpatch core module hasn't been updated yet to work with the latest upstream kernels, since we're slowly weaning off dependence on the kpatch core module and focusing our efforts on upstream livepatch. If you would like to try out kpatch, I'd recommend setting CONFIG_LIVEPATCH for your custom kernel and try compiling a patch module for kernel versions 4.4 (or 4.3?) or lower, since we haven't had a chance to update kpatch for the 4.5 kernels (with symbol positioning support).

**Comment by dandart** [comment]
Ah I may have misunderstood the purpose of this. I want to use Livepatch but I don't know what userspace tools to use.

**Comment by flaming-toast** [comment]
You can use the kpatch-build utilities to build patch modules for a livepatch enabled kernel :-) Just with kernel versions < 4.5.

**Comment by dandart** [comment]
Aha, gotcha. Thanks

**Comment by flaming-toast** [comment]
Closing issue for now, feel free to open up another issue if you run into any other problems.
