### ISSUE TITLE
Does kpatch support building patches for different versions of kernel in same environment?

### ISSUE THREAD

**Issue by vvoody** [dynup/kpatch#585]
Hi!

Let's say I have a few servers, Ubuntu 14.04, having same kernel package installed `linux-image-3.13.0-46-generic`. Unfortunately, they were not built at same time. Some of them have version `3.13.0-46.77`, some have `3.13.0-46.79`.

To build patches for these two versions of linux kernel, I have to setup two virtual machines to run `3.13.0-46.77` and `3.13.0-46.79`, then build patches in parallel. Another way is to install both kernel packages on single machine, build patches for .77 first then reboot with loading kernel .79 and build for it.

Questions:
* Is there a way to increase the efficiency of build patches for different linux kernel versions? Two versions are good for me, but in the future the number may become bigger.
* One patch built for one certain kernel version on some server, e.g. 3.13.0-46.79, can it be applied to other servers running exactly same kernel version (3.13.0-46.79)?

Thanks!
Best regards.

**Comment by arges** [comment]
You can use `kpatch-build` options to specify a specific git repository, vmlinux, config, etc. See `kpatch-build -h`. Second, building for one Linux version will most likely _not_ apply for another release due to ABI changes; you'll need to rebuild for each kernel ABI change.

**Comment by vvoody** [comment]
@arges Thanks, Chris.

For Q1, kpatch can specify kernel source, but kpatch requires debug symbol package, right? Say we run an system with kernel packages linux-image-3.13.0-46-generic, linux-headers-3.13.0-46-generic, linux-image-extra-3.13.0-46-generic and linux-tools-3.13.0-46-generic installed. This linux kernel release is 3.13.0-46-generic, but there are a few minor versions of this release, e.g. 3.13.0-46`.77` and 3.13.0-46`.79`. Now suppose I have source codes of both `.77` and `.79` and use option `-s` to specify which once by kpatch-build. Then, kpatch-build will look for `linux-image-$(uname -r)-dbgsym`. There are also two packages for dbgsym, e.g. linux-image-3.13.0-46-generic-dbgsym_3.13.0-46`.77`_amd64.ddeb and linux-image-3.13.0-46-generic-dbgsym_3.13.0-46`.79`_amd64.ddeb. But kpatch-build can't specify which dbgsym package, right? If I am running kernel from package 3.13.0-46`.77`, kpatch-build goes for 3.13.0-46`.77` dbgsym automatically. What if I want to build for 3.13.0-46`.79`? Hope you could understand this... Thanks.

For Q2. I mean that I built a patch on a server with linux-image-3.13.0-46-generic, package version is 3.13.0-46`.79`. Can I load this patch using kpatch on another server with exact linux-image-3.13.0-46-generic, package version is 3.13.0-46`.79`, not a different version? Is this officially supported?

Thanks.

**Comment by flaming-toast** [comment]
@vvoody I'm afraid there isn't a way to specify a specific debugsym package  w/ kpatch-build yet. Usually it's just way easier to use kpatch-build with a specific source directory if you want to build for another version. Yes, it is a bit annoying if you don't want to supply the sources yourself. Pull requests are always welcome. :-)
For question 2, the answer is technically yes, it is possible to load the patch module onto another server iff it is running the exact same kernel, **but** I think this would only work with livepatch modules, not the kpatch ones, since the kpatch core module checks against symbol addresses that were looked up in vmlinux at compile time (and these addresses could change between compiles, even if the kernel versions are the same). So while the answer is technically "yes, it is possible" I'd still recommend recompiling patch modules against each kernel.

**Comment by jpoimboe** [comment]
I think @vvoody 's questions have been answered, so I'm going to close this issue.  @vvoody if you have more questions, please reopen.  Or even better, use the kpatch mailing list.
