### ISSUE TITLE
unexpected unreconcilable difference

### ISSUE THREAD

**Issue by arges** [dynup/kpatch#599]
Use kernel sources before 09d9686047dbbe1cf4faa558d3ecc4aae2046054 and live patch as follows:

```
diff --git a/net/ipv4/netfilter/arp_tables.c b/net/ipv4/netfilter/arp_tables.c
index e255507..6f5c348 100644
--- a/net/ipv4/netfilter/arp_tables.c
+++ b/net/ipv4/netfilter/arp_tables.c
@@ -700,10 +700,10 @@ static int translate_table(struct xt_table_info *newinfo, void *entry0,
 		}
 	}
 
-	if (!mark_source_chains(newinfo, repl->valid_hooks, entry0)) {
+	/*if (!mark_source_chains(newinfo, repl->valid_hooks, entry0)) {
 		duprintf("Looping hook\n");
 		return -ELOOP;
-	}
+	}*/
 
 	/* Finally, each sanity check must pass */
 	i = 0;

```
If you build you'll notice the following:

```
$ kpatch-build issue1.diff
WARNING: Skipping gcc version matching check (not recommended)
ERROR: unable to find Module.symvers for kpatch core module
ERROR: can't find core module Module.symvers
Debian/Ubuntu distribution detected
Downloading the kernel source for 4.4.0-22-generic
Unpacking kernel source
Testing patch file
checking file net/ipv4/netfilter/arp_tables.c
Reading special section data
Building original kernel
Building patched kernel
Extracting new and modified ELF sections
ERROR: arp_tables.o: reference to static local variable uncond.52945 in mark_source_chains was removed
/usr/lib/kpatch/create-diff-object: unreconcilable difference
ERROR: 1 error(s) encountered. Check /home/arges/.kpatch/build.log for more details.
```

Looking at the code:
`mark_source_chains` calls `unconditional` which reads as follows:
```
/* All zeroes == unconditional rule. */
static inline bool unconditional(const struct arpt_arp *arp)
{
        static const struct arpt_arp uncond;

        return memcmp(arp, &uncond, sizeof(uncond)) == 0;
}
```
So 'uncond' is contained here.

It seems like this should be a patchable condition and perhaps create-diff-object is creating a false negative.

**Comment by jpoimboe** [comment]
This is due to the way kpatch tries to correlate static local variables between the old and new code.  Basically it errors out if you remove a static local.  This is pretty much a permanent limitation.

To work around it you'll basically need to get creative by changing the patch such that the static local `uncond` variable still exists.  It might be as simple as adding the variable to `translate_table()`.  And then you may or may not have to do something trivial with it to convince gcc not to optimize it away.

**Comment by flaming-toast** [comment]
@jpoimboe Just to clarify, is the reasoning behind this limitation to prevent potential data semantic changes? In other words, we cannot support situations where an old function references a static local (and might change it some way) and the corresponding new function no longer does, because we cannot guarantee that the data will continue to be used in the same way the old code (running kernel) expects it to be used.

**Comment by jpoimboe** [comment]
Static locals are basically global variables because they outlive the function's scope.  They need to be correlated so that the new function will use the old static local via a dynrela.  That way patching the function doesn't inadvertently reset the variable to zero; instead the variable keeps its old value.  Otherwise it could cause some surprising behavior.

But there are several complications with correlating them:
- There can be several variables with the same name, used by the same function.
- Some variables can even be used by multiple functions.

It's quite tricky to deal with all situations in the kernel and I had to rewrite the static local correlation code several times in the past to get it right.  In order for it to work properly, no existing references to static locals can be removed.

**Comment by flaming-toast** [comment]
@jpoimboe Ah, I see. Thanks for the clarification!

**Comment by arges** [comment]
@jpoimboe @flaming-toast 
Tried to sum up comments here in the patch guide document since this may be useful for future users.
Thanks!
