### ISSUE TITLE
don't create dynrelas for exported symbols used by patched modules

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#695]
@joe-lawrence saw the following errors when loading upstream commit `128394eff343fc6d2f32172f03e24829539c5835` on RHEL7 with kpatch.ko:

```
Skipped dynrela for copy_user_generic_unrolled (0xffffffffa0475942 <- 0xffffffff813211e0): the instruction has been changed already.
Skipped dynrela for copy_user_generic_unrolled (0xffffffffa0475a57 <- 0xffffffff813211e0): the instruction has been changed already.
```

It's running into issue #580, but I think that can be avoided by leaving `copy_user_generic_unrolled` as a normal relocation instead of converting it to a dynrela, because it's an exported symbol.  @flaming-toast would you agree, or am I missing an edge case when it comes to patching a module?  Is there any reason why a patch to a module would need a dynrela for an exported symbol?

**Comment by jpoimboe** [comment]
The only case I can think of where it would need a dynrela would be if the exported symbol is in another module.  In that case the relocation may need to be deferred, in case the other module hasn't been loaded yet.  But if it's defined by vmlinux, seems like it can just be a normal rela.

**Comment by flaming-toast** [comment]
@jpoimboe I think relas against exported symbols can be left as normal relas. 

Back before create-diff-object was made Module.symvers-aware, in the case of patching a module, we could not determine if a symbol was exported by vmlinux because all we had was the lookup symbol table for the module (and not Module.symvers, or vmlinux). It was a create-diff-object limitation at the time.

Now that this limitation in create-diff-object is gone, we can change create-diff-object such that dynrelas for exported symbols don't get created.

**Comment by flaming-toast** [comment]
@jpoimboe Minor clarification: for my previous comment I'm talking about exported vmlinux symbols.

I'm still thinking about what should happen when a module uses an exported symbol from another module that's not loaded...normally modprobe takes care of this kind of module dependency for us by loading any prerequisite modules first, but we don't rely on modprobe/depmod.
