### ISSUE TITLE
Question about the srcversion

### ISSUE THREAD

**Issue by ufo19890607** [dynup/kpatch#697]
Hi,
I generate a ko file using the the kpatch-build tool,but the ko does not contain the srcversion.Do I need to add other options for the kpatch-build? Why the ko file generated from the  kpatch-build is different from the general ko in the system.
filename:      /kpatch/builder/release/kpatch/3.10.0-327.36.3.el7.x86_64/kpatch-toa-v1-0-55cd6c2.ko
license:        GPL
rhelversion:    7.2
depends:        kpatch
vermagic:       3.10.0-327.36.3.el7.x86_64 SMP mod_unload modversions 
parm:           replace:replace all previously loaded patch modules (bool)

**Comment by flaming-toast** [comment]
You need to have CONFIG_SRCVERSION_ALL enabled for your kernel, otherwise the srcversion will only be generated for modules with a MODULE_VERSION() tag.

**Comment by joe-lawrence** [comment]
@flaming-toast - I thought *.el7 kernels already had `CONFIG_MODULE_SRCVERSION_ALL` set.  None of kpatch modules I've been building lately against  3.10.0-[200-600].el7.x86_64 kernels have srcversion module info.

**Comment by flaming-toast** [comment]
@joe-lawrence Hm, you are right. I'll look into the modpost script to see why srcversion isn't being generated for kpatch modules..

**Comment by flaming-toast** [comment]
So Joe pointed to an old comment from 2014 discussing srcversion for patch modules: https://github.com/dynup/kpatch/issues/343#issuecomment-53667657

In addition, I added a few prints to modpost to see where it was failing, and I hit this warning:
`WARNING: could not find .kpatch/tmp/patch/.output.o.cmd for .kpatch/tmp/patch/output.o`

srcversion is supposed to contain a checksum of all the source files that make up a module, but patch modules are special because they're made up of specifically selected elf sections and linked together into a sort of "frankenstein" module, as Josh once put it. Generating .output.o.cmd (which would contain a list of source files that make it up) doesn't make sense because it's not really built from source files...rather it's created by linking objects outputted by create-diff-object that contain only the necessary text sections to support a patch. So I think srcversions are inherently incompatible with kpatch modules. @ufo19890607 is there any reason why you need to have the srcversion for patch modules?

**Comment by ufo19890607** [comment]
@flaming-toast  I need to make patch modules for others .I know that each patch module has only one srcversion, so it can be used to distinguish different patch modules. If srcversions are inherently incompatible with kpatch modules, is there any way to make sure that the ko file loaded into the system is my ko ?

**Comment by flaming-toast** [comment]
@ufo19890607 Yes, you can dump the `.kpatch.checksum` section of the patch module. It contains a string checksum of the final output object built into the patch module. This should be sufficient to distinguish between different patch modules.
