### ISSUE TITLE
boot.o: changed section .init.text not selected for inclusion

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#724]
Hello,

while trying to live patch:
x86/acpi: Prevent out of bound access caused by broken ACPI

i got the following errors:

Extracting new and modified ELF sections
ERROR: boot.o: 2 unsupported section change(s)
boot.o: changed section .init.text not selected for inclusion
boot.o: changed section .rela.init.text not selected for inclusion

Greets,
Stefan

**Comment by joe-lawrence** [comment]
Hi @disaster123, livepatching the kernel is generally used to update kernel code that runs after boot, therefore patching any __init or early boot code is not supported.  (Hence the unsupported section complaints from kpatch-build.)

As far as I can tell, [x86/acpi: Prevent out of bound access caused by broken ACPI](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dad5ab0db8deac535d03e3fe3d8f2892173fa6a4) was coded to protect isa_irq_to_gsi[] at boot time.  Are there other instances where this array should be protected?  (I can't seem to find any references or callers to references outside of __init code.)  If so, then the livepatch solution needs to be unique from the upstream fix.

**Comment by disaster123** [comment]
*arg* you're totally right. My fault. Sorry about that.
