### ISSUE TITLE
testing: fedora 4.14.x kernels and ORC unwinder sections

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#785]
Seen when building the macro-hooks.patch on latest fedora:
```
% grep UNWINDER_ORC /boot/config-4.1*
/boot/config-4.14.16-300.fc27.x86_64:CONFIG_UNWINDER_ORC=y

ERROR: aio.o: 3 unsupported section change(s)
aio.o: found hook: kpatch_unload_aio_max_nr
aio.o: found hook: kpatch_load_aio_max_nr
aio.o: new function: kpatch_load_aio_max_nr
aio.o: new function: kpatch_unload_aio_max_nr
aio.o: changed section .orc_unwind_ip not selected for inclusion
aio.o: changed section .rela.orc_unwind_ip not selected for inclusion
aio.o: changed section .orc_unwind not selected for inclusion
/root/kpatch.joe/kpatch-build/create-diff-object: unreconcilable difference
ERROR: 1 error(s) encountered. Check /root/.kpatch/build.log for more details.
```

**Comment by jpoimboe** [comment]
That ORC guy is always breaking things.  Unfortunately I think we're going to have to treat the ORC sections as special sections, so we can strip the parts of the sections which don't apply to the patch module code.

Although... I have a new idea about how to simplify our special section handling.  Instead of stripping out unused portions of the special sections, I wonder if we can keep the sections wholesale, and instead just convert all of the unused relocations to dynrelas, so that the unused ones get relocated to point to kernel code, but are never used.  I could be forgetting some important detail, so I'm not 100% sure it would work, but if it did, we could get rid of all the special section nonsense in create-diff-object and the kpatch-build script.

**Comment by KernelKyupCom** [comment]
Hi there.
I've hit the same with 4.15.x
Did you have any chance to take a look at that?
Any suggestions where to start from ?

**Comment by jpoimboe** [comment]
I hope to get to it soon.  In the meantime, you can just downgrade the error to a warning.  The only downside is that any stack dumps involving the patch module won't work.

```diff --git a/kpatch-build/create-diff-object.c b/kpatch-build/create-diff-object.c
index 49d0aa9..2d2e73e 100644
--- a/kpatch-build/create-diff-object.c
+++ b/kpatch-build/create-diff-object.c
@@ -1247,7 +1247,6 @@ static void kpatch_verify_patchability(struct kpatch_elf *kelf)
 		if (sec->status == CHANGED && !sec->include) {
 			log_normal("changed section %s not selected for inclusion\n",
 				   sec->name);
-			errs++;
 		}
 
 		if (sec->status != SAME && sec->grouped) {
```
