### ISSUE TITLE
how to patch functions in section .spinlock.text?

### ISSUE THREAD

**Issue by haoren3696** [dynup/kpatch#825]
Hi, it seems that some functions in kernel/spinklock.c which is compiled in section .spinlock.text can not be patched by kpatch. Is there a way to support these functions?

**Comment by haoren3696** [comment]
> You can't patch functions that are forced into a specific section (in this case by __lockfunc attribute) directly

how abount __sched attriibute?  will kpatch support patch functions in kernel scheduler or any other similar cases?

**Comment by sm00th** [comment]
Same story, __sched is defined as follows:
```
#define __sched   __attribute__((__section__(".sched.text")))
```

So it forces the function to be placed in .sched.text and can't be patched directly.

**Comment by haoren3696** [comment]
Is it possible to develop kpatch support patch functions in .sched.text and .spinlock.text?

**Comment by jpoimboe** [comment]
The problem is that kpatch-build relies on the GCC `-ffunction-sections` flag to be able to easily do a binary diff on functions.  But that flag only works for functions in the `.text` section.

Some options for fixing this issue:
- Remove kpatch-build's reliance on the `-ffunction-sections` option (I believe this may be possible, but would be a lot of work)
- Add GCC `-ffunction-sections` support for for non-`.text` functions
