### ISSUE TITLE
find_local_syms() failures on optimized-out objectfiles

### ISSUE THREAD

**Issue by sm00th** [dynup/kpatch#910]
While testing f27 with meminfo-cmdline-rebuild-SLOW.patch I stumbled upon a couple examples when the whole objectfile is getting discarded during final vmlinux linking.

The two examples I have are:

arch/x86/lib/error-inject.c that is built if CONFIG_FUNCTION_ERROR_INJECTION is enabled but only used if CONFIG_BPF_KPROBE_OVERRIDE or CONFIG_FAIL_FUNCTION is enabled.

drivers/net/dsa/dsa_loop_bdinfo.c - not exactly sure what happens with this one, but it is missing from vmlinux (or any modules) as well.

It looks like config-dependency issues, but can we somehow detect cases like this?

**Comment by jpoimboe** [comment]
A few ideas:

- downgrade it to a warning and return EXIT_STATUS_NO_CHANGE like the "WARNING: FILE symbol not found in base"; or
- delay the error until after we detect that the file has changed, otherwise the lookup table won't be needed anyway; or
- similarly, just move the lookup_open() call to much later, after we've detected that the object file has changed.

I think I like the 3rd idea the best.  That way we'd only get an error if the object file actually changed.
