### ISSUE TITLE
kpatch-build should warn about static keys

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#946]
kpatch-build drops `__jump_table` sections from the special section handling, so static keys do not operate as expected.  (#931 "Livepatch does not handle static keys".)

We attempted including them (#937 "Add jump label support"), but it turned out that wasn't the full story as we ran into issues (#940 "Jump label support still cannot work".)

The main problem is that "special" livepatch symbols are not fully relocated before the jump label core code attempts to initialize them.  (See the call chain in the commit message for #944 Revert "create-diff-object: add jump label support".)

While we are waiting for a kernel fix (work in progress), we should:

1. Update the patch author's guide explaining these short comings
2. Warn the user (if we can) that functions referencing static keys have changed and that the patched code may not execute as intended.  In some cases simply loading the patch module may crash the host.

cc: @euspectre, @ufo19890607

**Comment by jpoimboe** [comment]
create-diff-object should be able to detect and warn on such cases by looking for .rela__jump_table relocations which reference a changed or included function.

The workaround would be for the user to switch the jump label usage to use static_key_enabled() instead.

**Comment by euspectre** [comment]
Yes, we discussed the ways to detect jump labels in https://github.com/dynup/kpatch/issues/931. They seem to work, but I'd like to experiment with them a bit more: lots of noise caused by tracepoints I guess. May be we could just skip the tracepoints there, not sure. Switching their implementation to static_key_enabled() and such may be quite tedious and error-prone.

Just for the record, the old kpatch core (which we still use for some kernels) also has issues if https://github.com/dynup/kpatch/pull/937 is applied to the build tools: the kernel crashes in jump_label_del_module() when the patch is replaced with a newer one. The list of jump labels got corrupted somehow, I am currently debugging this.

**Comment by jpoimboe** [comment]
If we want to skip warnings for tracepoints then we can ignore any jump label entry whose key begins with "__tracepoint".

**Comment by jpoimboe** [comment]
Here's an attempt at a patch: jpoimboe@879b33804df5bdfc54f50d34af8181e7c4fd8dd8

I think an error is more appropriate than a warning since this can cause undefined behavior and crashes.  The only problem is that this currently fails unit testing because one of the unit test binaries uses static keys in a patched function.

**Comment by euspectre** [comment]
> Here's an attempt at a patch: jpoimboe/kpatch@274157e

**Comment by euspectre** [comment]
@jpoimboe:
With your patch, it seems, no error will be output if a patched function uses both tracepoints and other jump labels. Right?

I guess, the check should look like this instead:

```C
+		if (jump_table) {
+			int jump_label = 0;
+
+			list_for_each_entry(rela, &sec->relas, list) {
+				if (rela->offset >= src_offset &&
+				    rela->offset < src_offset + group_size) {
+					if (strncmp(rela->sym->name, "__tracepoint_", 13))
+						jump_label = 1; /* may be, output the location here as well */
+				}
+
+			}
+
+			if (jump_label)
+				ERROR("A patched function uses jump labels, which aren't currently supported.  Use static_key_enabled() instead.");
```

Not tested yet.

**Comment by jpoimboe** [comment]
@euspectre You're right, my patch wasn't quite right, though I think your fix won't work either, because it's only the 3rd entry in the group which has the key name.

Printing the function which uses it would be nice as well.

I can try to work up a better patch (time willing).

**Comment by jpoimboe** [comment]
I was wary of hard-coding checking of the 3rd entry because the format of the jump table has changed over time (and may change in the future) but we may have to do it.

**Comment by euspectre** [comment]
For the record: I checked the patched kpatch-build with the kernel 3.10.0-957.1.3 from CentOS7 on the fix for CVE-2018-9568, just to see what would be found. Added debug prints for the relevant relas too and changed the error into a warning temporarily.

> Extracting new and modified ELF sections
> sock.o: changed function: sk_clone_lock
> sock.o: [DBG] jump label found: sk_clone_lock, addend 679, offset 432.
> sock.o: [DBG] jump label found: sk_clone_lock, addend 752, offset 440.
> sock.o: [DBG] jump label found: memcg_socket_limit_enabled, addend 0, offset 448.
> sock.o: WARNING: A patched function uses jump labels, which aren't currently supported.  Use static_key_enabled() instead.
> Patched objects: vmlinux

These references correspond to 'code', 'target' and 'key' fields of struct jump_entry, if I understand it right. And yes, it seems the problem is that the definition of struct jump_entry changed some time ago and it is

**Comment by jpoimboe** [comment]
Looking at both RHEL7 and upstream, and both x86 and power, the jump_entry format is always code/target/key.  The types vary, but in all cases I believe they use relocations for all of them.  So I think I can just hard-code that ordering of the fields in the code.

**Comment by jpoimboe** [comment]
@euspectre How about jpoimboe/kpatch@3461ed52d4b69750b9ec2250d851af56617f13fd ?

**Comment by euspectre** [comment]
Thanks, testing it now.

By the way, it would be good to output `key->sym->name` in that error message as well. That would help a lot in in the situations like CVE-2018-9568 where the usage of a static key is far from obvious due to inlines and #defines.

**Comment by jpoimboe** [comment]
Good idea.  I updated the patch with your suggestion: jpoimboe/kpatch@2cd2d27607566aee9590c367e615207ce1ce24c6

**Comment by euspectre** [comment]
I have tested the patch on the kernel 3.10.0-957.1.3.el7.x86_64 from CentOS 7 and on a couple of kernels from VZ7.

Looks good to me so far.

* The original fix for CVE-2018-9568 - kpatch-build correctly pointed out the usage of the static key.
* The fix for CVE-2018-9568 with the explicit static_key_enabled() instead of the static branch - no complaints, OK.
* A patch for __alloc_pages_nodemask(), a function where both tracepoints and static branches are used - kpatch-build detected the static branch and ignored all the tracepoints, OK.
* kpatch-build now spotted a few more rather difficult to find locations where `memcg_kmem_enabled_key` is used in VZ7 kernels, which is good.

Overall, the detection looks good.

**Comment by euspectre** [comment]
A patch for __sk_mem_raise_allocated() from the stable kernel 5.0.1 was processed OK as well: the usage of `memcg_sockets_enabled_key` was detected correctly.
