### ISSUE TITLE
documentation: i miss an information about the lifetime of a livepatch module

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#967]
I'm not sure whether the topic is clear most probably not.

What i'm missing is when should a module be loaded, when unloaded? Something like a best practice.

For example if i build a newer livepatch for my kernel which also contains the changes of the old livepatch. Should i just load the newer one or should i unload the old one before?

This one https://github.com/dynup/kpatch/blob/master/contrib/kpatch.service also contains an unload on stop which means, when the server reboots or shuts down it will unload all patches. Is this really a good idea on shutdown? It may contain fixes for unmounting filesystems, ...

**Comment by jpoimboe** [comment]
If you have a cumulative livepatch which is a superset of the old one, the old one can just be left loaded.  That way there's no window of time where the system is unpatched.  And also you don't have to unload the patch, which may introduce additional risk.  It can just be left inert, in memory.

Upstream livepatch now has a better way to deal with this.  If you set klp_patch.replace, the new patch will automatically replace and disable the old patch(es).  This is the best way to do it because a) any compiler optimization changes between the patches could potentially change which functions are affected; and b) it allows you to unload the old patch afterwards, if you want.

Please feel free to suggest any changes to the patch author guide to make it clearer.

Also, that kpatch.service file looks like a bug - I don't think it's a good idea to unload the patch when shutting down, as it introduces unnecessary risk.

**Comment by disaster123** [comment]
Thanks a lot for clarification. I think your text might just go directly to the doc ;-)

regarding klp_patch.replace - i found:
https://lore.kernel.org/patchwork/patch/921683/

but this is not in our 4.19 kernel so i need to stick to the default behaviour.
